### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#105]
Waiting until GPU merge to new master -> MFC main branch.

**Comment by henryleberre** [comment]
Now that we are considering upstreaming MFlowCode/MFC-develop into MFlowCode/MFC, we should, as you alluded to in your first comment, assign MFC a new semantic version. The last indication of a version I can find on the organization's list of repositories seems to be 3.0. I assume there have been enough breaking & significant changes since then to necessitate a bump in the major version.

I presume we would then use MFlowCode/MFC for active development so we can keep work (issues, branches, PRs, and Projects) in a single place. Once we merge a PR into the `master`/`production` branch(es), we would tag the associated commit and publish a new GitHub release, with an accurate major/minor/patch semantic version. We could better keep track of changes between versions and better isolate issues.

The documentation could easily be updated to save a copy of each release's documentation, which can be viewed online, through a link like https://mflowcode.github.io/3.1.4/, while the latest documentation remains available at https://mflowcode.github.io/.
