### ISSUE TITLE
Doxygen problems: script + CI + badge

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#21]
* Need a script that auto-builds the Doxygen documentation on CI and adds a README badge.
* Doxygen will require graphviz (or something like this) to build the documentation properly.
* Right now Doxygen will complain that `../icon.ico` is missing. I don't remember what the icon ever was, so we can remove it for now.
* The landing page of the Doxygen involves a lot of HTML that just repeats what is already in the readme. Not DRY!
* The Doxygen is also copied over to the website located here mfc-caltech.github.io which has a repository here: https://github.com/MFC-Caltech/MFC-Caltech.github.io, again not DRY

**Comment by sbryngelson** [comment]
Wishlist: Having the Doxygen build via a Sphinx wrapper a la https://stackoverflow.com/questions/36064976/using-doxygen-in-read-the-docs would fix several items at once!

**Comment by sbryngelson** [comment]
[this](https://github.com/adafruit/ci-arduino/blob/master/doxy_gen_and_deploy.sh) and [this](https://github.com/adafruit/Adafruit_NeoPixel/blob/master/.github/workflows/githubci.yml)?

**Comment by henryleberre** [comment]
I found this:
- https://ostueker.github.io/Example_Fortran/UsingSphinxFortran.html
- https://sphinx-fortran.readthedocs.io/en/latest/

**Comment by sbryngelson** [comment]
The problem with this strategy is it requires changes the code documentation syntax throughout the entire code, which would be a lot of work. I think the links I posted before allowed one to convert to something link Sphinx without changing syntax, though I have no tried it. Another concern is that sphinx fortran appears to be dead, with no real commits in years.

**Comment by sbryngelson** [comment]
@henryleberre Minor update: I deleted all content on `mfc-caltech.github.io` and just made it a pointer to the newer website, `mflowcode.github.io`, so there's no need to duplicate effort there.

**Comment by henryleberre** [comment]
@sbryngelson We have auto-building and publishing Doxygen documentation [here](https://henryleberre.github.io/MFC-DOC/index.html), fully integrated with our CMake system. Since the landing page was out of date, I temporarily replaced it with the README. The few links that are missing from the original can easily be added. Sharing the README would be quite DRY and - thus - more maintainable.

I added a modern theme that gets automatically downloaded and applied for a nicer esthetic as well as enhanced mobile support (you previously couldn't browse the actual documentation on such devices).

Currently, only the website is built and published but we could easily make the PDF documentation automatically and link to it from the website. Here is the [CMakeLists.txt](https://github.com/henryleberre/MFC/blob/GPU-docs/CMakeLists.txt) file responsible for building MFC and its documentation. It's ~360 LOC since I was able to abstract away some repetitive tasks that were done the same way for each code using macros (Fypp & Doxygen).

To generate the documentation with CMake:
```console
$ cmake -DMFC_BUILD_DOC=ON ..
$ make install -j $(nproc)
```

pre_process, simulation, post_process, and the landing page get built at the same time. You can override the default installation prefix with `-DCMAKE_INSTALL_PREFIX=<your install directory>` as with any CMake project.

The documentation CI:
- Clones MFC
- Builds & installs the documentation
- Clones the Github pages website with a private Github access token (hidden from view using Github secrets)
- Deletes everything from it except `.github/` (so the website can be built)
- Copies over the installed documentation
- Pushes it

The website is setup from a ready-made Github action that publishes static webpages like this one. Are the latex files of the MFC user guide available?

**Comment by sbryngelson** [comment]
Looks great to me, we can publish this version! The user guide files are available, I can send them to you, I'm thinking that the TeX version of the user guide can just be absorbed into the website. Probably more maintainable that way.

**Comment by henryleberre** [comment]
Great! Do you mean we can create markdown files as a replacement or that the TeX version should be built from source when the documentation is generated by CMake, and then linked from the website? I assume it's the former. It would also help make the README shorter. In that case, having the TeX files would be a great resource to make them.

**Comment by sbryngelson** [comment]
[v1.1.zip](https://github.com/MFlowCode/MFC-develop/files/9333321/v1.1.zip)

**Comment by henryleberre** [comment]
Something like [this](https://henryleberre.github.io/MFC-DOC/landing/md_running.html#autotoc_md27) ? I was able to get Latex rendering with MathJax. Github natively supports it for Markdown, and you have to enable it in Doxygen, providing a custom configuration file so that it acts _like_ Github, also providing for inline math. I only had to slightly modify the larger expressions.

**Comment by sbryngelson** [comment]
Beautiful! Yes, that's great.
