### ISSUE TITLE
Throw error if attempting to use more MPI ranks than GPUs

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#79]
Just as the title says. Our current device bindings only support 1 MPI rank per GPU. I think this is reasonable. Using more than 1 rank per GPU would require nvidia-mps, which is a very platform-specific thing and doesn't actually help us anyway. 

@henryleberre Can you add a little error flag in `m_python_proxy.py` that does: `if (#GPUs > 0 .and. # MPI ranks /= # GPUs) print('When using GPUs you must have have the same number of MPI ranks and GPUs'); quit()`

**Comment by henryleberre** [comment]
This check is present in [run.py](https://github.com/MFlowCode/MFC-develop/blob/master/run/run.py) for `-e parallel` since #120. 

https://github.com/MFlowCode/MFC-develop/blob/b82be667fd96885f624140833702ba8884aeb0c9/bootstrap/run/run.py#L89-L91

For serial mode, where one uses a single node, we could check the number of (NVidia) GPUs with:
```console
nvidia-smi -L | wc -l
```
However, this command does take a significant amount of time to run (1.029s on WSL).
The other alternatives that would work with AMD GPUs aren't as reliable, and may list more GPUs than available on some systems, as they use `lspci` to check for `VGA` adapters.

Perhaps a better approach would be to handle this in [p_main.fpp](https://github.com/MFlowCode/MFC-develop/blob/GPU/src/simulation_code/p_main.fpp), where we can compare the number of local MPI ranks (`local_size`) and GPUs with `acc_get_num_devices`, since the local (sub)communicator is created with ranks that can share memory (`MPI_COMM_TYPE_SHARED`).

https://github.com/MFlowCode/MFC-develop/blob/fc3c5513e52bb0e8ab2961c92aa4d617b817acf8/src/simulation_code/p_main.fpp#L84-L86

https://github.com/MFlowCode/MFC-develop/blob/fc3c5513e52bb0e8ab2961c92aa4d617b817acf8/src/simulation_code/p_main.fpp#L90

**Comment by sbryngelson** [comment]
Definitely want to check this in `p_main.fpp`, it's less hacky this way (and more transparent to the user).  Thanks!
