### ISSUE TITLE
Syntax error on build

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#83]
OS: MacOS 12.1, M1Max
Compiler: GCC11
Shell: Bash 5.X
Branch: Master
Issue: Just built MFC using `./mfc.sh -t MFC -j 8 --build` and, while is seems to have worked, it did throw a few syntax errors in the middle of the build process (in the middle of environment checks).

```
├─ Environment Checks
|  ├─ Required command-line utilities...
|  |  ├─ Found 7/7. (Success)
|  ├─ Compiler Checks
expr: syntax error
expr: syntax error
|  ├─ Passing. (Success)
├─ Building Package mfc
```

After compiling all tests pass.

**Comment by henryleberre** [comment]
This issue should now be resolved @sbryngelson. I managed to get access to a mac to test on. It was caused by the particular version of bash macOS is using. It's either because it's outdated or because it isn't fully GNU compatible. It turns out that that turning `\=\=` into `\=` was enough for it to work. The double-equal sign for equality isn't supported on macOS.

**Comment by sbryngelson** [comment]
is there a PR?

**Comment by henryleberre** [comment]
I'll make one right now for my two latest resolved issues.
