### ISSUE TITLE
Behavior of `mfc.sh` with no arguments

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#85]
Right now calling `mfc.sh` with no arguments gives unexpected behavior (it rebuilds everything? I'm not sure). In any case, it should probably just default to printing the help a la `mfc.sh -h`.

**Comment by henryleberre** [comment]
Currently, simply running `mfc.sh` builds `MFC` with the user's default configuration from their `mfc.user.yaml`. This is because:
- `--build` is implied when no other "action" is requested (`--test`, `--clean`, ...).
- `-t|--targets` defaults to `MFC`.
- `-cc` defaults to `release-cpu` (per ` mfc.user.yaml`).
- `-j` defaults to `1` (per ` mfc.user.yaml`).

These defaults were introduced to make `mfc.sh` less verbose to use but I definitely understand that - if they don't read the documentation - they would have to _guess_ that `./mfc.sh -h|--help` exists and that the script offers them a lot of useful features.

Would you think that adding a warning when they run `mfc.sh` for **first time** would be sufficient?

The _"no argument build"_ is quite useful in my opinion: if you are developing, it can be quite cumbersome to have to specify each time your desired configuration. e.g if you wanted to build MFC for GPU without all these convenience features, the command would become:
```shell
[build] mfc.sh --build -j 8 -t MFC -cc release-gpu
[test]  mfc.sh --test       -t MFC -cc release-gpu
```

**Comment by sbryngelson** [comment]
For a new user there is no reason to believe that running `mfc.sh` with no arguments builds MFC. In fact it goes against usual protocol of makefiles and such. Since MFC is the default target, that should be able to be left out of the above commands you cite. Also, `-j` is not a required argument. So `mfc.sh --build` makes sense as the minimum possible command to build MFC. `mfc.sh` with no arguments should just print the help.

**Comment by henryleberre** [comment]
I see, I'll just remove the _defaultness_ of `--build`
