### ISSUE TITLE
Cloning dependencies results in larger than needed downloads and directories

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#87]
After a fresh build of MFC the `/build` directory takes up 99% of the space (aside from MFC's own `.git/`). This can be tracked down to the `build/common` directory:

```
[I] common/src $ dus
 62M	fftw3
 76M	silo
523M	hdf5
```

and subsequently

```
[I] src/hdf5 $ du -h -d 1
3.8M	./c++
1.6M	./release_docs
 80M	./tools
 19M	./hl
 58M	./test
1.0M	./bin
1.2M	./config
5.3M	./java
532K	./examples
448K	./m4
3.3M	./fortran
218M	./.git
9.8M	./testpar
118M	./src
523M	.
```

Solution: For the git cloned dependencies can we just do a depth=1 clone or something to avoid downloading these large `.git` directories that aren't used or needed? e.g. `git clone --depth=1 <package URL here>`

Ref: https://stackoverflow.com/questions/11497457/git-clone-without-git-directory

**Comment by henryleberre** [comment]
Wow, `hdf5` is huge! I tried adding `--depth=1` but the issue is that we `git checkout <hash>` after we clone a repository to a use a version we have tested. As `--depth` omits quite a bit of the repository's history, we can't `git checkout` anymore and it fails. Unfortunately, `git` doesn't seem to have a feature letting you clone a repository at a desired commit.
However, deleting `.git` afterwards is perfectly fine.

**Comment by sbryngelson** [comment]
The issue isn't really space but rather download time.

**Comment by henryleberre** [comment]
If we delete `.git` we might as well delete the entire source directory once it's built if it's a `common` target.

**Comment by henryleberre** [comment]
@sbryngelson We can perhaps try to use a zipped version

**Comment by henryleberre** [comment]
However, the `tar` python package is notoriously slow because it was written in Python.

**Comment by sbryngelson** [comment]
You could try something like this.

**Comment by sbryngelson** [comment]
Just get rid of this change. No need to delete git dir.
